services:
  postgres:
    image: postgres:17
    container_name: vactracker-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: py7837
      POSTGRES_DB: vactracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: vactracker-backend
    restart: always
    ports:
      - "3100:3100"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: